// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byctxbgkyctcjryxlkvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5Y3R4YmdreWN0Y2pyeXhsa3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNzcyNzQsImV4cCI6MjA2Njc1MzI3NH0.MzQx1mHSRJCSsnH8Kj-K4c3fxMiTbhmYiY_IsVs25KY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);